### ISSUE TITLE
Some crashes not recorded to scoreboard

### ISSUE THREAD

**Issue by JohnHaTrick** [huevosabio/aa228-final#13]
Sometimes it appears the agent goes right through another vehicle, and yet the scoreboard does not reflect the crash.

I understand that because bumper distance is not yet taken into account, that lot's of near misses appear to be crashes, but I'm talking about full on run throughs not being recorded.

Why is this?

It is the same reason the MDP didn't change lanes to avoid the crash?

**Comment by huevosabio** [comment]
I noticed this, and was trying to debug it without much success. Some could be addressed by the bumper thing #16, but I believe there are instances where the car simple passes one or two of them without incurring any penalty. We should find a way to replicate

**Comment by JohnHaTrick** [comment]
I agree on the replication.  I think setting up some contrived intruder situations would make debugging more effective.  The randomness makes putting the agent into the same situation over again impossible.

**Comment by JohnHaTrick** [comment]
Just witnessed a crash not avoided or recorded.  It was an easy one to change lanes around too...  Too bad it was a random set-up.  Really need to try and replicate it under repeatable conditions.

**Comment by huevosabio** [comment]
I've noticed some issues with the calc rewards (namely, it was not taking into account the acceleration!), but now I've corrected them. Crashes seem to be recording now, will close this upon further inspection

**Comment by huevosabio** [comment]
Still some overlaps happen and do not get recorded.

**Comment by JohnHaTrick** [comment]
So, I'm not sure x_2 = x_1 * v*t + (1/2)*a*t^2 is the right way to go...

It's a stark change from the way everything's been put together so far.  Especially in the effective meaning of the accelerate actions up to this point.  So far, acceleration has meant "instantaneous change in speed."  While this is not physically feasible, I think it's simple and fits in with the way we're doing instantaneous lane changes.

To redefine acceleration as dv/dt changes a lot.

**Comment by huevosabio** [comment]
I guess there's no harm on doing so, we can go back to instantaneous changes of speed.

**Comment by huevosabio** [comment]
Crashes work as expected.
