### ISSUE TITLE
2 lane maneuvers not utilized to avoid crashes.

### ISSUE THREAD

**Issue by JohnHaTrick** [huevosabio/aa228-final#14]
It appears that many crashes occur when the agent would have to move over 2  lanes in order to avoid multiple intruders.

In such cases, the agent seems to get over 1 lane if the crash can be delayed by a time-step (gamma may reduce predicted crash cost).

In other cases, the agent drives right through the car in front it if both lanes would result in a crash.  Can be explained by lane-change cost.

**Comment by huevosabio** [comment]
We are not allowing 2 lane maneuvers are we?

**Comment by JohnHaTrick** [comment]
We are not.

I mean that the agent could perform 2 successive lane changes.  Like if it starts on the bottom lane, it could change to the center, and then on the next action go up to the top.  But, it doesn't seem to see these options.

**Comment by huevosabio** [comment]
Let's address this after #20
