### ISSUE TITLE
Do we need to take into account bumper distance?

### ISSUE THREAD

**Issue by JohnHaTrick** [huevosabio/aa228-final#16]
I would prefer not to, at this point.  I think it's an interesting task to delegate to MPC.  I am going to work up a slick graphic to show how MPC handles these edge cases.

Obstacle: the math is not so obvious to me. We could write a series of if statements, though.

However, if the agent does think he can cut it so close, that may encourage it to plan unfeasible routes...  Ok maybe watching for the bumper is a good idea.

**Comment by huevosabio** [comment]
Proposal:

so we have two positions, `x0` and `x1`, now our distance is

```
dist = x1 - x0
```
let `w` be the length of a car, then your effective distance is 

```
eff_dist = abs(x1 - x0) - w
```

thus I would add to the current checks a condition that states that for the current state `s` and state after action `sp` the effective distance is greater than zero: `eff_dist > 0`

would this work?

**Comment by huevosabio** [comment]
I've included this in my branch, will close once we agree to merge into master
